#!/bin/bash
python3 -c "import sys, collections; print('\n'.join([f'{host}\t{count}' for host, count in collections.Counter([line.split('\t')[0] for line in open(sys.argv[1])]).most_common(11)]))" /var/log/mysql/error.log
