#!/bin/bash
python3 -c "from collections import Counter; import sys; [print(f'{host}\t{count}') for host, count in Counter([line.split('\t')[0] for line in open(sys.argv[1])]).most_common(11)]" /var/log/mysql/error.log

