#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59, and limits the output to the first 70 lines

hour=0
while [ $hour -le 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        echo "$hour:$minute"
        ((minute++))
    done
    ((hour++))
done | head -n 70
