#!/usr/bin/env bash

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0 # Exit cleanly after handling the signal
}

# Set up trap for SIGTERM
trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

